FROM python:bullseye

ARG http_proxy
ARG https_proxy

ENV http_proxy ${http_proxy}
ENV https_proxy ${https_proxy}
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENV FLASK_APP=app

ENV FLASK_ENV=dev

RUN python3 -m venv $VIRTUAL_ENV

COPY docker-entrypoint.sh /usr/local/bin/

RUN sed -i -e 's/\r$//' /usr/local/bin/docker-entrypoint.sh

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# RUN flask db upgrade
# RUN flask configure-db

RUN chmod +x docker-entrypoint.sh
RUN ./docker-entrypoint.sh

# ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 5000

# CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
CMD ["python3", "run.py"]