name: fly.io Deploy

on: 
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          SECRET_WORD_REGISTRATION=${{ secrets.SECRET_WORD_REGISTRATION }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY=${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          EOF
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: LOG_LEVEL=debug flyctl deploy #--remote-only
      - run: flyctl deploy #--remote-only